server:
  port: 8080
  enable_tls: false

minio:
  enabled: true
  endpoint: ${MINIO_ENDPOINT}
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  bucket_name: voiceflow-audio
  use_ssl: ${MINIO_USE_SSL}

stt:
  provider: azure  # 可选值：azure、google、local

tts:
  provider: google  # 可选值：azure、google、local

llm:
  provider: openai  # 可选值：openai、local

azure:
  stt_key: ${AZURE_STT_KEY}
  tts_key: ${AZURE_TTS_KEY}

google:
  stt_key: ${GOOGLE_STT_KEY}
  tts_key: ${GOOGLE_TTS_KEY}

openai:
  api_key: ${OPENAI_API_KEY}

logging:
  level: info