server:
  port: 18080
  enable_tls: false

Web:
  port: 18090

minio:
  enabled: true
  endpoint: ${MINIO_ENDPOINT}
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  bucket_name: 'telepace-pipeline'
  secure: true  # 如果需要使用 HTTPS 连接，设置为 true

stt:
  provider: azure  # 可选值：azure、google、local

tts:
  provider: google  # 可选值：azure、google、local

llm:
  provider: openai  # 可选值：openai、local

azure:
  stt_key: "your_azure_stt_key"
  tts_key: "your_azure_tts_key"
  region: "eastus"

google:
  stt_key: "your_google_stt_key"
  tts_key: "your_google_tts_key"

openai:
  api_key: "your_openai_api_key"

logging:
  level: info