server:
  port: 18080
  enable_tls: false

minio:
  enabled: true
  endpoint: "localhost:9000"
  access_key: "your_access_key"
  secret_key: "your_secret_key"
  bucket_name: "telepace-pipeline"
  secure: true
  storage_path: "voiceflow/audio/"

stt:
  # 可选值：azure、 google、 local、 assemblyai-ws、 volcengine、 aws
  provider: assemblyai

tts:
  # 可选值：azure、 google、 local、 volcengine
  provider: volcengine

llm:
  # 可选值：openai、local
  provider: openai

azure:
  stt_key: ""
  tts_key: ""
  region: "eastus"

google:
  stt_key: "your_google_stt_key"
  tts_key: "your_google_tts_key"

aws:
    region: "us-east-1"
    access_key_id: ''
    secret_access_key: ''

openai:
  api_key: ""
  # OPENAI_BASE_URL='https://api.lqqq.cc/v1'       # Global provider
  # OPENAI_BASE_URL='https://api.chatanywhere.cn'  # International version
  # OPENAI_BASE_URL='https://api.chatanywhere.tech'  # Domestic version
  # OPENAI_BASE_URL='https://api.chatanywhere.tech'  # Domestic version
  base_url: ""

volcengine:
  # 语音识别(STT)配置
  stt:
    ws_url: ''
    uid: "test"
    rate: 16000
    format: "pcm"
    bits: 16
    channel: 1
    codec: "pcm"
    access_key: ''
    app_key: ''
    # 小时版：volc.bigasr.sauc.duration
    # 并发版：volc.bigasr.sauc.concurrent
    resource_id: 'volc.bigasr.sauc.duration'
  
  # 语音合成(TTS)配置
  tts:
    ws_url: "wss://openspeech.bytedance.com/api/v1/tts/ws_binary"
    app_id: "your_app_id"
    token: "your_token"
    cluster: "volcano_tts"
    voice_type: "zh_female_sajiaonvyou_moon_bigtts"
    encoding: "mp3"
    speed_ratio: 1.0
    volume_ratio: 1.0
    pitch_ratio: 1.0

# 日志配置
logging:
  # 日志级别（选项：debug 调试）、info（信息）、warn（警告）、error（错误）、fatal（致命错误））
  level: "info"
  # 日志格式（选项：json（JSON 格式）、text（文本格式））
  format: "text"
  # 日志文件路径（留空则仅输出到标准输出）
  filename: ""
  # 日志文件轮转前的最大大小（单位：MB）
  max_size: 100
  # 要保留的旧日志文件的最大数量
  max_backups: 3
  # 保留旧日志文件的最大天数
  max_age: 28
  # 是否压缩旧日志文件
  compress: true
  # 是否在日志中包含调用者信息
  report_caller: true

assemblyai:
  api_key: ""