name: Test repository spelling check
on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main
    workflow_dispatch:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest e
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling of md
      uses: crate-ci/typos@master
      with: 
        files: 
            ./CONTRIBUTING.md
            ./README.md
            
    - name: Use custom config file
      uses: crate-ci/typos@master
      with: 
        files: ./file.txt
        config: ./myconfig.toml

    - name: Ignore implicit configuration file
      uses: crate-ci/typos@master
      with: 
        files: ./file.txt
        isolated: true

    - name: Writes changes in the local checkout
      uses: crate-ci/typos@master
      with: 
        write_changes: true