name: Check for typos
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for typos
      uses: codespell-project/actions-codespell@v2
      with:
        check_filenames: true
        skip: .git,*.png,*.jpg
        ignore_words_file: .github/workflows/codespell_ignore_words.txt
        exclude_file: docs/CODEOWNERS
        paths: ./CONTRIBUTING.md ./README.md

